import torch
from torchvision.models import efficientnet_b4, EfficientNet_B4_Weights
import torch.nn as nn
import sys
import os
sys.path.append('/sfs/weka/scratch/ced9mq/ds6050/Final Project')
from model import SkinEffnetB4

def count_params(module):
    return sum(p.numel() for p in module.parameters())

def trainable_params(module):
    return sum(p.numel() for p in module.parameters() if p.requires_grad)

def print_model_summary(model, input_tensor, meta_tensor=None, title="", file=None):
    def out(line=""):
        print(line)
        if file:
            file.write(line + "\n")

    out(f"\n{'='*110}")
    out(f"  {title}")
    out(f"{'='*110}")
    out(f"{'Layer':<60} {'Output Shape':<25} {'Params':>10} {'Trainable':>10}")
    out(f"{'-'*110}")

    hooks = []
    layer_info = []

    def make_hook(name):
        def hook(module, input, output):
            if isinstance(output, torch.Tensor):
                shape = tuple(output.shape)
            else:
                shape = "non-tensor"
            layer_info.append({
                "name": name,
                "shape": shape,
                "params": count_params(module),
                "trainable": trainable_params(module)
            })
        return hook

    for name, module in model.named_modules():
        if len(list(module.children())) == 0:
            hooks.append(module.register_forward_hook(make_hook(name)))

    with torch.no_grad():
        if meta_tensor is not None:
            model(input_tensor, meta_tensor)
        else:
            model(input_tensor)

    for h in hooks:
        h.remove()

    for info in layer_info:
        out(f"{info['name']:<60} {str(info['shape']):<25} {info['params']:>10,} {info['trainable']:>10,}")

    out(f"{'-'*110}")
    out(f"{'TOTAL':<60} {'':25} {count_params(model):>10,} {trainable_params(model):>10,}")
    out(f"{'TRAINABLE TOTAL':<60} {'':25} {'':10} {trainable_params(model):>10,}")

x = torch.randn(1, 3, 380, 380)
meta = torch.randn(1, 15)

output_path = os.path.join(
    '/sfs/weka/scratch/ced9mq/ds6050/Final Project',
    'model_parameter_summary.txt'
)

with open(output_path, 'w') as f:

    f.write("EfficientNet-B4 Model Parameter Summary\n")
    f.write("Input resolution: 380x380, Classes: 8, Meta features: 15\n")
    f.write("Generated by model_summary.py\n")

    # --- Variant 1: TL, no MetaBlock ---
    model_tl = SkinEffnetB4(pretrained=True, use_metablock=False, num_classes=8)
    model_tl.eval()
    print_model_summary(model_tl, x, meta_tensor=None,
                        title="Variant 1 — Transfer learning, no MetaBlock, 8 classes",
                        file=f)

    # --- Variant 2: Scratch, no MetaBlock ---
    model_scratch = SkinEffnetB4(pretrained=False, use_metablock=False,
                                  dropout_p=0.5, num_classes=8)
    model_scratch.eval()
    print_model_summary(model_scratch, x, meta_tensor=None,
                        title="Variant 2 — From scratch, no MetaBlock, dropout=0.5, 8 classes",
                        file=f)

    # --- Variant 3: TL, MetaBlock ---
    model_meta = SkinEffnetB4(pretrained=True, use_metablock=True,
                               num_classes=8, meta_num=15)
    model_meta.eval()
    print_model_summary(model_meta, x, meta_tensor=meta,
                        title="Variant 3 — Transfer learning, MetaBlock, 8 classes, 15 meta features",
                        file=f)

    # --- Variant 4: Scratch, MetaBlock ---
    model_meta_scratch = SkinEffnetB4(pretrained=False, use_metablock=True,
                                       dropout_p=0.5, num_classes=8, meta_num=15)
    model_meta_scratch.eval()
    print_model_summary(model_meta_scratch, x, meta_tensor=meta,
                        title="Variant 4 — From scratch, MetaBlock, dropout=0.5, 8 classes, 15 meta features",
                        file=f)

    # --- Side by side comparison ---
    comparison_lines = [
        f"\n{'='*60}",
        "  Parameter count comparison",
        f"{'='*60}",
        f"{'Variant':<45} {'Total params':>15}",
        f"{'-'*60}",
    ]
    variants = [
        ("TL, no MetaBlock",        model_tl),
        ("Scratch, no MetaBlock",   model_scratch),
        ("TL, with MetaBlock",      model_meta),
        ("Scratch, with MetaBlock", model_meta_scratch),
    ]
    for name, m in variants:
        comparison_lines.append(f"{name:<45} {count_params(m):>15,}")
    comparison_lines.append(f"{'='*60}")

    for line in comparison_lines:
        print(line)
        f.write(line + "\n")

print(f"\nSummary written to: {output_path}")